// @ts-check
import { formatNumberLocale } from './_env.js';
import factors from './factors.js';
import contingency from './contingency.js';
import numeric from './numeric.js';
import variants from './variants.js';
import charts from './charts/index.js';
import snapshots from './snapshots.js';
import { getBinaryLabels, getColumnTypeLabel, getDefaultMissingLabel, getTableHeaders, normalizeLanguage, translate } from '../i18n/index.js';

/**
 * @typedef {Object} Column
 * @property {string} col_hash
 * @property {string} col_label
 * @property {'q'|'n'|'l'} col_type
 * @property {string=} col_sep
 * @property {boolean=} col_del
 * @property {any[]=} raw_values
 * @property {{labels?: string[]}=} col_values
 */

/**
 * @typedef {{columns: string[], rows: Array<Record<string,string>>, [k:string]: any}} TableLike
 */

/**
 * @typedef {{analysis: Array<{ predictor: string, response?: string|null, predictor_type: string, response_type?: string|null, table: TableLike }>, test_legend: Array<{method:string,symbol:string}>}} CombinedAnalysis
 */

/** @type {Record<string, any>} */
const ns = {};

/**
 * Retrieve a column by hash from a parsed database payload.
 * @param {{columns?: Column[]}|null|undefined} database
 * @param {string} colHash
 * @returns {Column|null}
 */
ns.getColumn = function (database, colHash) {
  if (!database || !Array.isArray(database.columns)) return null;
  return database.columns.find((col) => col?.col_hash === colHash) ?? null;
};

/**
 * Retrieve a column by hash and decode its **stored** values.
 *
 * Deliberately does NOT apply `meta.replacements` / `meta.processing` — it is the "as stored" view.
 * For the final, analysis-facing values call `factors.resolveVariable(database, colHash, variantIndex)`
 * directly; this helper is a thin wrapper around it with `applyProcessing: false`.
 *
 * @param {{columns?: Column[]}|null|undefined} database Parsed database payload returned by parseColumns
 * @param {string} colHash Column hash to match
 * @param {number|null} [variantIndex=null] Optional variant index from col_vars
 * @returns {{ column: Column|null, variant: any|null, rawValues: any[] }}
 */
ns.getColumnValues = function (database, colHash, variantIndex = null) {
  const resolved = factors.resolveVariable(database, colHash, variantIndex, { applyProcessing: false });
  if (!resolved) return { column: null, variant: null, rawValues: [] };
  return { column: resolved.column, variant: resolved.variant, rawValues: resolved.values };
};

/**
 * Append a variant to the specified column, seeding the base variant when needed.
 * @param {{columns?: Column[]}|null|undefined} database Parsed database payload returned by parseColumns
 * @param {string} colHash Column hash to match
 * @param {any} newVariant Variant payload generated by variants.createVariant
 * @returns {any}
 */
ns.addVariant = function (database, colHash, newVariant) {
  if (!newVariant || typeof newVariant !== 'object') {
    throw new Error('Variant payload is required to add a variant.');
  }
  if (!database || !Array.isArray(database.columns)) {
    throw new Error('Invalid database payload; expected an object with columns.');
  }
  const column = ns.getColumn(database, colHash);
  if (!column) {
    throw new Error(`Column with hash ${colHash} not found in database.`);
  }
  if (!Array.isArray(column.col_vars) || column.col_vars.length === 0) {
    const colLabel = column.col_label ?? "Original";
    column.col_vars = [{
      var_label: colLabel,
      meta: { kind: 'original' }
    }];
  }
  column.col_vars.push(newVariant);
  snapshots.refreshColumnHashes(database, colHash);
  return newVariant;
};

/**
 * Replace a variant at `editIndex` in the specified column and re-replay every
 * downstream variant (`editIndex + 1` and beyond) against the updated chain.
 *
 * The replay walks variants in order, reads each one's `meta.recipe`, and re-runs
 * `variants.createVariant` against the current `col_vars` state — so variants that
 * reference the edited one (via `sourceVarIndex`) get rebuilt with fresh data, and
 * variants that reference earlier (untouched) variants are re-derived equivalently.
 *
 * Graceful degradation: when a variant has no recipe or its replay throws, the old
 * variant is preserved and a warning is collected. `var_label` of the old variant
 * is always carried over to the replacement.
 *
 * Mutates `database` (consistent with `addVariant`). The `newVariant` argument is
 * not mutated.
 *
 * @param {{columns?: Column[]}|null|undefined} database Parsed database payload.
 * @param {string} colHash Column hash to match.
 * @param {number} editIndex Index in `col_vars` of the variant being replaced. Must be ≥ 1 (the base variant at index 0 is not editable).
 * @param {any} newVariant Variant payload generated by `variants.createVariant`.
 * @returns {{warnings: string[]}}
 */
ns.replaceVariantAt = function (database, colHash, editIndex, newVariant) {
  if (!newVariant || typeof newVariant !== 'object') {
    throw new Error('Variant payload is required to replace a variant.');
  }
  if (!database || !Array.isArray(database.columns)) {
    throw new Error('Invalid database payload; expected an object with columns.');
  }
  if (!Number.isInteger(editIndex) || editIndex < 1) {
    throw new Error(`Invalid editIndex ${editIndex}; must be an integer ≥ 1 (the base variant is not editable).`);
  }
  const column = ns.getColumn(database, colHash);
  if (!column) {
    throw new Error(`Column with hash ${colHash} not found in database.`);
  }
  if (!Array.isArray(column.col_vars) || editIndex >= column.col_vars.length) {
    throw new Error(`editIndex ${editIndex} out of bounds for col_vars length ${column.col_vars?.length ?? 0}.`);
  }

  /** @type {string[]} */
  const warnings = [];
  const oldDownstream = column.col_vars.slice(editIndex + 1);
  column.col_vars[editIndex] = newVariant;
  // Trim downstream — we'll rebuild them one by one against the updated chain.
  column.col_vars.length = editIndex + 1;

  oldDownstream.forEach((oldVar) => {
    const recipe = oldVar?.meta?.recipe;
    const label = oldVar?.var_label ?? 'unnamed';
    if (!recipe) {
      column.col_vars.push(oldVar);
      warnings.push(`Variant "${label}" has no stored recipe; kept previous data — may be stale.`);
      return;
    }
    try {
      const replayed = variants.createVariant(column, recipe);
      if (oldVar.var_label) replayed.var_label = oldVar.var_label;
      column.col_vars.push(replayed);
    } catch (err) {
      column.col_vars.push(oldVar);
      warnings.push(`Variant "${label}" recipe failed against the updated chain (${err?.message || err}); kept previous data.`);
    }
  });

  snapshots.refreshColumnHashes(database, colHash);
  return { warnings };
};

/**
 * Remove the variant at `removeIndex` from `col_vars`, cascade-deleting any variants
 * that depend on it (directly or transitively via `sourceVarIndex`), and re-replay the
 * remaining downstream variants against the updated chain with adjusted indices.
 *
 * Cascade detection walks `col_vars` once in order, growing a set of "dependent" indices:
 * any variant whose `meta.recipe.sourceVarIndex` is in the set is added to the set.
 *
 * Preserved downstream variants are re-encoded via `variants.createVariant` with their
 * recipe's `sourceVarIndex` remapped to the new position. Variants with no recipe or
 * whose replay throws are silently kept in place (no warning) — only cascade removals
 * are reported via the `warnings` array, translated through `core/i18n`.
 *
 * Mutates `database`. Throws on invalid input (unknown column, removeIndex < 1 or out
 * of bounds — the base variant is not removable).
 *
 * @param {{columns?: Column[]}|null|undefined} database
 * @param {string} colHash
 * @param {number} removeIndex Index in `col_vars` of the variant to remove. Must be ≥ 1.
 * @param {{lang?: string}} [options]
 * @returns {{warnings: string[]}}
 */
ns.removeVariantAt = function (database, colHash, removeIndex, options = {}) {
  if (!database || !Array.isArray(database.columns)) {
    throw new Error('Invalid database payload; expected an object with columns.');
  }
  if (!Number.isInteger(removeIndex) || removeIndex < 1) {
    throw new Error(`Invalid removeIndex ${removeIndex}; must be an integer ≥ 1 (the base variant is not removable).`);
  }
  const column = ns.getColumn(database, colHash);
  if (!column) {
    throw new Error(`Column with hash ${colHash} not found in database.`);
  }
  if (!Array.isArray(column.col_vars) || removeIndex >= column.col_vars.length) {
    throw new Error(`removeIndex ${removeIndex} out of bounds for col_vars length ${column.col_vars?.length ?? 0}.`);
  }

  const lang = normalizeLanguage(options?.lang);
  const oldVars = column.col_vars;

  // Step 1: identify the set of variants to remove (target + transitive dependents).
  /** @type {Set<number>} */
  const dependentSet = new Set([removeIndex]);
  for (let i = removeIndex + 1; i < oldVars.length; i++) {
    const srcIdx = oldVars[i]?.meta?.recipe?.sourceVarIndex;
    if (Number.isInteger(srcIdx) && dependentSet.has(srcIdx)) {
      dependentSet.add(i);
    }
  }

  // Step 2: build old → new index remap for preserved variants.
  /** @type {Map<number, number>} */
  const indexMap = new Map();
  let newIdx = 0;
  for (let i = 0; i < oldVars.length; i++) {
    if (!dependentSet.has(i)) {
      indexMap.set(i, newIdx);
      newIdx += 1;
    }
  }

  // Step 3: pre-removeIndex variants reference indices < removeIndex (sourceVarIndex < self
  // by contract), all preserved with unchanged positions — copy intact, no replay needed.
  column.col_vars = oldVars.slice(0, removeIndex);

  // Step 4: re-replay each preserved variant after removeIndex, in order, with sourceVarIndex
  // remapped. Failures are silent (variant kept as-is, original col_values preserved).
  for (let i = removeIndex + 1; i < oldVars.length; i++) {
    if (dependentSet.has(i)) continue;
    const oldVar = oldVars[i];
    const recipe = oldVar?.meta?.recipe;
    if (!recipe) {
      column.col_vars.push(oldVar);
      continue;
    }
    const oldSrcIdx = recipe.sourceVarIndex;
    const remappedSrc = Number.isInteger(oldSrcIdx) ? indexMap.get(oldSrcIdx) : undefined;
    if (remappedSrc === undefined) {
      column.col_vars.push(oldVar);
      continue;
    }
    const adjustedRecipe = { ...recipe, sourceVarIndex: remappedSrc };
    try {
      const replayed = variants.createVariant(column, adjustedRecipe);
      if (oldVar.var_label) replayed.var_label = oldVar.var_label;
      column.col_vars.push(replayed);
    } catch {
      column.col_vars.push(oldVar);
    }
  }

  // Step 5: warnings — only for cascade-removed dependents (not the explicitly removed one).
  /** @type {string[]} */
  const warnings = [];
  Array.from(dependentSet)
    .sort((a, b) => a - b)
    .forEach((idx) => {
      if (idx === removeIndex) return;
      const label = oldVars[idx]?.var_label ?? `index ${idx}`;
      warnings.push(translate('variants.warnings.cascadeDeleted', lang, { label }));
    });

  snapshots.refreshColumnHashes(database, colHash);
  return { warnings };
};

/**
 * Build row-wise objects from column-major raw_values.
 * @param {Column[]} columns
 * @returns {Array<Record<string, any>>}
 */
ns.getRowwiseData = function (columns) {
  if (!Array.isArray(columns)) return [];
  const n = Math.max(...columns.map(c => c.raw_values?.length || 0));
  const rows = [];
  for (let i = 0; i < n; i++) { const row = {}; columns.forEach(col => { row[col.col_hash] = col.raw_values?.[i] ?? null; }); rows.push(row); }
  return rows;
};

/**
 * Convert named-row objects into a 2D matrix following provided column order.
 * @param {string[]} columns
 * @param {Array<Record<string, any>>} rows
 * @returns {any[][]}
 */
ns.tabularRowsToMatrix = function (columns, rows) { return rows.map(row => columns.map(col => row[col])); };

/**
 * Frequency table for qualitative values.
 * @param {Array<string|null|undefined>} values
 * @param {(ctx:{count:number,percent:number,total:number})=>string=} formatFn
 * @param {{missing_label?:string, include_missing?:boolean, lang?:string}=} options
 * @param {{labels?: string[]|null}=} param3
 * @returns {TableLike}
 */
ns.summarize_q = function (values, formatFn = null, options = {}, { labels = null } = {}) {
  /** @type {Record<string, number>} */
  const freqMap = {}; let missingCount = 0; const total = values.length;
  const lang = normalizeLanguage(options?.lang);
  const missingLabel = options?.missing_label ?? getDefaultMissingLabel(lang);
  const includeMissing = options?.include_missing ?? true;
  const [variableHeader, descriptionHeader] = getTableHeaders(lang);
  values.forEach(val => { if (factors.isMissingValue(val)) { missingCount++; return; } const v = String(val).trim(); freqMap[v] = (freqMap[v] || 0) + 1; });
  const sortedLabels = labels ?? Object.keys(freqMap).sort();
  const rows = sortedLabels.map(label => { const count = freqMap[label] || 0; const percent = (count / total) * 100; const percentFormatted = formatNumberLocale(percent, 1, lang); const cell = formatFn ? formatFn({ count, percent, total }) : `${count} (${percentFormatted}%)`; return { [variableHeader]: label, [descriptionHeader]: cell }; });
  if (includeMissing && missingCount > 0) { const percent = (missingCount / total) * 100; const percentFormatted = formatNumberLocale(percent, 1, lang); const cell = formatFn ? formatFn({ count: missingCount, percent, total }) : `${missingCount} (${percentFormatted}%)`; rows.push({ [variableHeader]: missingLabel, [descriptionHeader]: cell }); }
  return { columns: [variableHeader, descriptionHeader], rows, summary: { total, total_is_full: true }, lang };
};

/**
 * Frequency table for list-like qualitative values (split by a separator).
 * @param {Array<string|null|undefined>} values
 * @param {string=} sep
 * @param {(ctx:{count:number,percent:number,total:number})=>string=} formatFn
 * @param {{missing_label?: string, include_missing?: boolean, lang?: string}=} options
 * @returns {TableLike}
 */
ns.summarize_l = function (values, sep = ';', formatFn = null, options = {}) {
  if (!Array.isArray(values)) return { columns: [], rows: [], summary: { total: 0, total_is_full: true } };
  /** @type {Record<string, number>} */
  const counts = {}; let missingCount = 0; const total = values.length;
  const lang = normalizeLanguage(options?.lang);
  const missingLabel = options?.missing_label ?? getDefaultMissingLabel(lang);
  const includeMissing = options?.include_missing ?? true;
  const [variableHeader, descriptionHeader] = getTableHeaders(lang);
  // isMissingValue with col_type 'l' covers both a blank cell and a separator-only one (';'),
  // which is why there is no second `items.length === 0` check here.
  values.forEach(v => { if (factors.isMissingValue(v, 'l', sep)) { missingCount++; return; } String(v).split(sep).map(s => s.trim()).filter(Boolean).forEach(item => { counts[item] = (counts[item] || 0) + 1; }); });
  const rows = Object.entries(counts).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0])).map(([level, count]) => { const percent = (count / total) * 100; const percentFormatted = formatNumberLocale(percent, 1, lang); const cell = formatFn ? formatFn({ count, percent, total }) : `${count} (${percentFormatted}%)`; return { [variableHeader]: level, [descriptionHeader]: cell }; });
  if (includeMissing && missingCount > 0) { const percent = (missingCount / total) * 100; const percentFormatted = formatNumberLocale(percent, 1, lang); const cell = formatFn ? formatFn({ count: missingCount, percent, total }) : `${missingCount} (${percentFormatted}%)`; rows.push({ [variableHeader]: missingLabel, [descriptionHeader]: cell }); }
  return { columns: [variableHeader, descriptionHeader], rows, summary: { total, total_is_full: true }, lang };
};

/**
 * Expand list-like predictors into binary yes/no columns and summarize against qualitative responses.
 * Returns one chi-square table per list item.
 * @param {Array<string|null|undefined>} listValues
 * @param {string[]} responseVals
 * @param {(ctx:{count:number,percent:number,rowTotal:number,colTotal:number})=>string=} formatFn
 * @param {{lang?:string}=} options
 * @param {{separator?:string,predictorLabel?:string|null,responseLabel?:string|null,lang?:string}=} meta
 * @returns {Array<{label:string,predictor_label?:string|null,predictor_label_stripped?:string|null,response_label?:string|null,table:TableLike}>}
 */
ns.summarize_l_q = function (listValues, responseVals, formatFn = null, options = {}, meta = {}) {
  const separator = meta?.separator ?? ';';
  const predictorLabel = meta?.predictorLabel ?? null;
  const responseLabel = meta?.responseLabel ?? null;
  const lang = normalizeLanguage(meta?.lang ?? options?.lang);
  const includePrefix = meta?.includePrefix ?? true;
  const cleanedPredictor = predictorLabel ? predictorLabel.replace(/[\s\p{P}]+$/u, '') : predictorLabel;
  const { columns: binaryColumns = {} } = numeric.decomposeListAsBinaryCols(listValues, separator, options);
  const results = [];
  Object.entries(binaryColumns).forEach(([label, binVals]) => {
    try {
      const table = contingency.summarize_q_q(binVals, responseVals, formatFn, options);
      const displayLabel = includePrefix && (cleanedPredictor || predictorLabel)
        ? `${cleanedPredictor || predictorLabel}: ${label}`
        : label;
      results.push({
        label,
        display_label: displayLabel,
        predictor_label: predictorLabel,
        predictor_label_stripped: cleanedPredictor,
        response_label: responseLabel,
        table
      });
    } catch (e) {
      const warnMessage = translate('warnings.summarizeFailure', lang, { label, context: predictorLabel ?? '' });
      console.warn(`${warnMessage}:`, e.message);
    }
  });
  return results;
};

/**
 * Profile B dispatcher: paired analysis across K ≥ 2 response columns (same individuals,
 * different momentos). Type-locked to the first response: all responses must share its type.
 * Currently supports numeric (paired t / Wilcoxon / Friedman) and binary qualitative
 * (McNemar / Cochran's Q). List responses and non-binary qualitative are rejected with
 * a translated warning surfaced via `table.warning`.
 *
 * @param {any[]} columns Resolved column objects (built by `runAnalysis`).
 * @param {Array<{col_hash:string, col_var_index?:number|null, col_label:string}>} responses
 * @param {Record<string,any>} options
 * @param {Set<string>} flagsUsed
 * @param {string} lang
 * @returns {{predictor:null, response:string|null, predictor_type:null, response_type:string|null, table:any}|null}
 */
ns.summarizePaired = function (columns, responses, options, flagsUsed, lang) {
  if (responses.length < 2) {
    flagsUsed.add('has_paired');
    return {
      predictor: null,
      response: responses[0]?.col_label || null,
      predictor_type: null,
      response_type: null,
      table: { warning: translate('warnings.pairedTooFewMomentos', lang) }
    };
  }
  // Cross-DB guard: paired analysis assumes same-individual row alignment, which only
  // holds within a single database. Cross-DB responses would produce silently bogus
  // pairings (rows truncated to min length, indices treated as same individual across DBs).
  const dbIds = new Set(responses.map((/** @type {any} */ r) => r.database_id));
  if (dbIds.size > 1) {
    flagsUsed.add('has_paired');
    return {
      predictor: null,
      response: responses[0]?.col_label || null,
      predictor_type: null,
      response_type: null,
      // The offending database ids are deliberately not surfaced: a Bubble UUID is not
      // actionable. Which database each variable came from belongs in the element summary UI.
      table: { warning: translate('warnings.pairedMultiDbNotAllowed', lang) }
    };
  }
  const resolvedCols = responses.map((r) =>
    columns.find((c) => c.col_hash === r.col_hash && c.col_var_index === (r.col_var_index ?? null))
      || columns.find((c) => c.col_hash === r.col_hash)
  );
  if (resolvedCols.some((c) => !c)) return null;
  /** @type {string[]} */
  const types = resolvedCols.map((c) => c.col_type);
  const firstType = types[0];
  // Type-lock: reject mixed responses.
  if (types.some((t) => t !== firstType)) {
    flagsUsed.add('has_paired');
    return {
      predictor: null,
      response: responses[0]?.col_label || null,
      predictor_type: null,
      response_type: firstType,
      // Deduped and translated: the user picked variables, not `q`/`n`/`l` codes, and a repeated
      // type in the list ('qualitativa, qualitativa, numérica') reads as noise.
      table: { warning: translate('warnings.pairedMixedTypes', lang, {
        types: [...new Set(types)].map((/** @type {string} */ t) => getColumnTypeLabel(t, lang)).join(', ')
      }) }
    };
  }
  const labels = responses.map((r) => r.col_label);
  if (firstType === 'n') {
    flagsUsed.add('has_paired_n');
    const arrays = resolvedCols.map((c) => c.raw_values || []);
    if (options?.mode === 'chart') {
      const chart = charts.chart_paired_n(arrays, labels, { ...options, lang }, {
        numericLabel: responses[0]?.col_label || ''
      });
      return /** @type {any} */ ({
        predictor: null,
        response: labels.join(' × '),
        predictor_type: null,
        response_type: 'n',
        chart
      });
    }
    const table = numeric.summarize_n_paired(arrays, labels, null, flagsUsed, { ...options, lang });
    return {
      predictor: null,
      response: labels.join(' × '),
      predictor_type: null,
      response_type: 'n',
      table
    };
  }
  if (firstType === 'q') {
    // Binary check: all responses must have ≤ 2 distinct non-empty levels.
    const levelSets = resolvedCols.map((c) => new Set((c.raw_values || []).map((v) => v?.toString().trim()).filter(Boolean)));
    const allBinary = levelSets.every((s) => s.size <= 2 && s.size >= 1);
    if (!allBinary) {
      flagsUsed.add('has_paired');
      const maxLevels = Math.max(...levelSets.map((s) => s.size));
      return {
        predictor: null,
        response: responses[0]?.col_label || null,
        predictor_type: null,
        response_type: 'q',
        table: { warning: translate('warnings.pairedNonBinaryQ', lang, { levels: maxLevels }) }
      };
    }
    // Use the union of observed levels as the binary pair.
    const unionLevels = [...new Set(levelSets.flatMap((s) => [...s]))].sort();
    if (unionLevels.length !== 2) {
      flagsUsed.add('has_paired');
      return {
        predictor: null,
        response: responses[0]?.col_label || null,
        predictor_type: null,
        response_type: 'q',
        table: { warning: translate('warnings.pairedNonBinaryQ', lang, { levels: unionLevels.length }) }
      };
    }
    flagsUsed.add('has_paired_q');
    const arrays = resolvedCols.map((c) => c.raw_values || []);
    if (options?.mode === 'chart') {
      const chart = charts.chart_paired_q(arrays, labels, { ...options, lang }, {
        levels: unionLevels,
        qualitativeLabel: responses[0]?.col_label || ''
      });
      return /** @type {any} */ ({
        predictor: null,
        response: labels.join(' × '),
        predictor_type: null,
        response_type: 'q',
        chart
      });
    }
    const table = contingency.summarize_q_binary_paired(arrays, labels, null, { ...options, lang }, { levels: unionLevels });
    return {
      predictor: null,
      response: labels.join(' × '),
      predictor_type: null,
      response_type: 'q',
      table
    };
  }
  if (firstType === 'l') {
    flagsUsed.add('has_paired');
    return {
      predictor: null,
      response: responses[0]?.col_label || null,
      predictor_type: null,
      response_type: 'l',
      table: { warning: translate('warnings.pairedListNotSupported', lang) }
    };
  }
  return null;
};

/**
 * Cross-tabulation of a qualitative predictor vs a list response.
 *
 * The list response is decomposed into binary (Yes/No) columns per item, and each binary
 * column is treated as the response in a `summarize_q_q` call against the qualitative
 * predictor. Mirror of `summarize_l_q` with predictor/response axes swapped.
 *
 * @param {string[]} predictorVals Qualitative predictor values (one per row).
 * @param {string[]} responseVals List response values (semi-colon-separated by default).
 * @param {((ctx:{count:number,percent:number,rowTotal:number,colTotal:number})=>string)|null} [formatFn]
 * @param {Record<string,any>} [options]
 * @param {{separator?:string, predictorLabel?:string|null, responseLabel?:string|null, lang?:string, includePrefix?:boolean}} [meta]
 * @returns {Array<{label:string, display_label:string, predictor_label:string|null, response_label:string|null, response_label_stripped:string|null, table:any}>}
 */
ns.summarize_q_l = function (predictorVals, responseVals, formatFn = null, options = {}, meta = {}) {
  const separator = meta?.separator ?? ';';
  const predictorLabel = meta?.predictorLabel ?? null;
  const responseLabel = meta?.responseLabel ?? null;
  const lang = normalizeLanguage(meta?.lang ?? options?.lang);
  const includePrefix = meta?.includePrefix ?? true;
  const cleanedResponse = responseLabel ? responseLabel.replace(/[\s\p{P}]+$/u, '') : responseLabel;
  const { columns: binaryColumns = {} } = numeric.decomposeListAsBinaryCols(responseVals, separator, options);
  const results = [];
  Object.entries(binaryColumns).forEach(([label, binVals]) => {
    try {
      const table = contingency.summarize_q_q(predictorVals, binVals, formatFn ?? undefined, options);
      const displayLabel = includePrefix && (cleanedResponse || responseLabel)
        ? `${cleanedResponse || responseLabel}: ${label}`
        : label;
      results.push({
        label,
        display_label: displayLabel,
        predictor_label: predictorLabel,
        response_label: responseLabel,
        response_label_stripped: cleanedResponse,
        table
      });
    } catch (e) {
      const warnMessage = translate('warnings.summarizeFailure', lang, { label, context: responseLabel ?? '' });
      console.warn(`${warnMessage}:`, e.message);
    }
  });
  return results;
};

/**
 * Cross-tabulation of a list predictor vs a list response with explicit subset selection.
 *
 * Both columns are decomposed into binary (Yes/No) item columns. For each pair
 * `(predItem ∈ predSubset, respItem ∈ respSubset)`, a 2×2 contingency table is built via
 * `contingency.summarize_q_q`. Items in the subsets that do not occur in the data are
 * skipped silently.
 *
 * The subset gate is enforced by the dispatcher in `summarizePredictors` — without
 * both subsets, the dispatch emits a warning instead of calling this helper.
 *
 * @param {string[]} predictorVals List predictor values.
 * @param {string[]} responseVals List response values.
 * @param {((ctx:{count:number,percent:number,rowTotal:number,colTotal:number})=>string)|null} [formatFn]
 * @param {Record<string,any>} [options]
 * @param {{predictorSep?:string, responseSep?:string, predictorLabel?:string|null, responseLabel?:string|null, predSubset?:string[], respSubset?:string[], lang?:string, includePrefix?:boolean}} [meta]
 * @returns {Array<{predictor_item:string, response_item:string, display_predictor:string, display_response:string, table:any}>}
 */
ns.summarize_l_l = function (predictorVals, responseVals, formatFn = null, options = {}, meta = {}) {
  const predictorSep = meta?.predictorSep ?? ';';
  const responseSep = meta?.responseSep ?? ';';
  const predictorLabel = meta?.predictorLabel ?? null;
  const responseLabel = meta?.responseLabel ?? null;
  const lang = normalizeLanguage(meta?.lang ?? options?.lang);
  const includePrefix = meta?.includePrefix ?? true;
  const predSubset = Array.isArray(meta?.predSubset) ? meta.predSubset.filter(Boolean) : [];
  const respSubset = Array.isArray(meta?.respSubset) ? meta.respSubset.filter(Boolean) : [];
  if (!predSubset.length || !respSubset.length) return [];

  const cleanedPredictor = predictorLabel ? predictorLabel.replace(/[\s\p{P}]+$/u, '') : predictorLabel;
  const cleanedResponse = responseLabel ? responseLabel.replace(/[\s\p{P}]+$/u, '') : responseLabel;

  const { columns: predBinary = {} } = numeric.decomposeListAsBinaryCols(predictorVals, predictorSep, options);
  const { columns: respBinary = {} } = numeric.decomposeListAsBinaryCols(responseVals, responseSep, options);

  const results = [];
  for (const pItem of predSubset) {
    if (!predBinary[pItem]) continue;
    for (const rItem of respSubset) {
      if (!respBinary[rItem]) continue;
      try {
        const table = contingency.summarize_q_q(predBinary[pItem], respBinary[rItem], formatFn ?? undefined, options);
        const displayPred = includePrefix && (cleanedPredictor || predictorLabel)
          ? `${cleanedPredictor || predictorLabel}: ${pItem}`
          : pItem;
        const displayResp = includePrefix && (cleanedResponse || responseLabel)
          ? `${cleanedResponse || responseLabel}: ${rItem}`
          : rItem;
        results.push({
          predictor_item: pItem,
          response_item: rItem,
          display_predictor: displayPred,
          display_response: displayResp,
          table
        });
      } catch (e) {
        const warnMessage = translate('warnings.summarizeFailure', lang, { label: `${pItem} × ${rItem}`, context: predictorLabel ?? '' });
        console.warn(`${warnMessage}:`, e.message);
      }
    }
  }
  return results;
};

/**
 * Compare a numeric response across binary "presence" groups derived from a list predictor.
 *
 * The list predictor is decomposed into binary (Yes/No) columns per item, and each item
 * becomes the grouping variable in a `summarize_n_q` call against the numeric response.
 * Mirror of `summarize_l_q` for the `l × n` case.
 *
 * @param {string[]} predictorVals List predictor values.
 * @param {string[]} responseVals Numeric response values.
 * @param {Function|null} [formatFn]
 * @param {Set<string>|null} [flagsUsed]
 * @param {Record<string,any>} [options]
 * @param {{separator?:string, predictorLabel?:string|null, responseLabel?:string|null, lang?:string, includePrefix?:boolean}} [meta]
 * @returns {Array<{label:string, display_label:string, predictor_label:string|null, predictor_label_stripped:string|null, response_label:string|null, table:any}>}
 */
ns.summarize_l_n = function (predictorVals, responseVals, formatFn = null, flagsUsed = null, options = {}, meta = {}) {
  const separator = meta?.separator ?? ';';
  const predictorLabel = meta?.predictorLabel ?? null;
  const responseLabel = meta?.responseLabel ?? null;
  const lang = normalizeLanguage(meta?.lang ?? options?.lang);
  const includePrefix = meta?.includePrefix ?? true;
  const cleanedPredictor = predictorLabel ? predictorLabel.replace(/[\s\p{P}]+$/u, '') : predictorLabel;
  const { columns: binaryColumns = {} } = numeric.decomposeListAsBinaryCols(predictorVals, separator, options);
  const results = [];
  Object.entries(binaryColumns).forEach(([label, binVals]) => {
    try {
      // summarize_n_q signature is (numericVals, groupingVals). The binary Yes/No column
      // is the grouping variable; the numeric response is summarized within each group.
      const table = numeric.summarize_n_q(responseVals, binVals, formatFn, flagsUsed, options);
      const displayLabel = includePrefix && (cleanedPredictor || predictorLabel)
        ? `${cleanedPredictor || predictorLabel}: ${label}`
        : label;
      results.push({
        label,
        display_label: displayLabel,
        predictor_label: predictorLabel,
        predictor_label_stripped: cleanedPredictor,
        response_label: responseLabel,
        table
      });
    } catch (e) {
      const warnMessage = translate('warnings.summarizeFailure', lang, { label, context: predictorLabel ?? '' });
      console.warn(`${warnMessage}:`, e.message);
    }
  });
  return results;
};

/**
 * Compare a numeric predictor across binary "presence" groups derived from a list RESPONSE.
 *
 * Axis-inverted wrapper over `summarize_l_n`. The statistic is identical in both directions —
 * `summarize_n_q` always takes the numeric column first and the binary item as the grouping
 * variable — so only the source of each array flips. (Contrast `summarize_q_l`, which had to be a
 * full copy of `summarize_l_q` because there the binary moves between the predictor and response
 * positions of `summarize_q_q`.)
 *
 * The list label always drives the per-item prefix, so `display_label` reads "Clinics: fever"
 * whichever side the list sits on.
 *
 * @param {string[]} predictorVals Numeric predictor values.
 * @param {string[]} responseVals List response values.
 * @param {Function|null} [formatFn]
 * @param {Set<string>|null} [flagsUsed]
 * @param {Record<string,any>} [options]
 * @param {{separator?:string, predictorLabel?:string|null, responseLabel?:string|null, lang?:string, includePrefix?:boolean}} [meta]
 * @returns {Array<{label:string, display_label:string, predictor_label:string|null, predictor_label_stripped:string|null, response_label:string|null, table:any}>}
 */
ns.summarize_n_l = function (predictorVals, responseVals, formatFn = null, flagsUsed = null, options = {}, meta = {}) {
  return ns.summarize_l_n(responseVals, predictorVals, formatFn, flagsUsed, options, {
    separator: meta?.separator,
    predictorLabel: meta?.responseLabel, // the LIST column — supplies the item prefix
    responseLabel: meta?.predictorLabel, // the NUMERIC column
    lang: meta?.lang,
    includePrefix: meta?.includePrefix
  });
};

/**
 * Build a map of statistical test methods to display symbols.
 * @param {string[]} methods
 * @param {{symbol_style?: 'numeric'|'alpha'}=} options
 * @returns {Record<string,string>}
 */
ns.generateTestSymbolMap = function (methods, options) {
  const style = options?.symbol_style ?? 'numeric'; const uniqueMethods = [...new Set(methods)];
  const numericSym = ['¹', '²', '³', '⁴', '⁵', '⁶', '⁷', '⁸', '⁹', '¹⁰']; const alpha = ['ᵃ', 'ᵇ', 'ᶜ', 'ᵈ', 'ᵉ', 'ᶠ', 'ᵍ', 'ʰ', 'ᶦ', 'ʲ'];
  const base = (style === 'alpha' ? alpha : numericSym); const map = {}; uniqueMethods.forEach((method, i) => { map[method] = base[i] || `(${i + 1})`; }); return map;
};


/**
 * Merge caller options with the defaults that Statz uses during runAnalysis.
 * @param {Record<string, any>=} options
 * @returns {Record<string, any>}
 */
ns.getDefaultAnalysisOptions = function (options = {}) {
  const lang = normalizeLanguage(options?.lang);
  const normalized = { ...options, lang };

  const alphaValue = Number(normalized.alpha);
  normalized.symbol_style = normalized.symbol_style ?? 'numeric';
  normalized.alpha = Number.isFinite(alphaValue) ? alphaValue : 0.05;

  const numericStats = Array.isArray(normalized.stat_options_numeric) && normalized.stat_options_numeric.length
    ? normalized.stat_options_numeric.slice()
    : ['min', 'max', 'mean_sd', 'n_missing'];
  normalized.stat_options_numeric = numericStats;

  const groupedStats = Array.isArray(normalized.stat_options_by_group) && normalized.stat_options_by_group.length
    ? normalized.stat_options_by_group.slice()
    : ['mean_sd'];
  normalized.stat_options_by_group = groupedStats;

  const statOptions = Array.isArray(normalized.stat_options) && normalized.stat_options.length
    ? normalized.stat_options.slice()
    : groupedStats.slice();
  normalized.stat_options = statOptions;

  normalized.percent_by = ['row', 'col', 'total'].includes(normalized.percent_by) ? normalized.percent_by : 'col';
  normalized.adjust_kruskal = normalized.adjust_kruskal ?? 'bonferroni';
  normalized.include_missing = normalized.include_missing ?? true;
  normalized.label_list_with_column = normalized.label_list_with_column ?? true;
  normalized.with_residuals = normalized.with_residuals ?? true;
  normalized.with_effect_sizes = normalized.with_effect_sizes === true;
  normalized.effect_size_type = (/** @type {any} */ (normalized).effect_size_type) === 'risk_ratio' ? 'risk_ratio' : 'odds_ratio';
  // Chart mode: defaults to 'table' for backward compatibility. When 'chart', the dispatcher
  // emits Plotly figure specs in `entry.chart` instead of cross-tab data in `entry.table`.
  normalized.mode = (/** @type {any} */ (normalized).mode) === 'chart' ? 'chart' : 'table';
  normalized.chart_theme = (/** @type {any} */ (normalized).chart_theme) ?? 'gray';
  normalized.chart_point_size = Number.isFinite(Number((/** @type {any} */ (normalized).chart_point_size)))
    ? Number((/** @type {any} */ (normalized).chart_point_size)) : 8;
  normalized.chart_show_boxplot = (/** @type {any} */ (normalized).chart_show_boxplot) === true;
  // Points+crossbar layer (numeric charts): default true preserves current behavior.
  // Both this and chart_show_boxplot together control the numeric-chart layer stack;
  // both off ⇒ empty axes (chart builders emit `data: []` but keep the layout).
  /** @type {any} */ (normalized).chart_show_points = (/** @type {any} */ (normalized).chart_show_points) !== false;
  // Crossbar central tendency for the points layer: 'median' avoids outlier pull on
  // asymmetric distributions; anything other than 'median' falls back to 'mean'.
  /** @type {any} */ (normalized).chart_central_tendency = (/** @type {any} */ (normalized).chart_central_tendency) === 'median' ? 'median' : 'mean';
  normalized.chart_label_format = ['n', 'p', 'np'].includes((/** @type {any} */ (normalized).chart_label_format))
    ? (/** @type {any} */ (normalized).chart_label_format) : 'n';
  normalized.chart_paired_show_lines = (/** @type {any} */ (normalized).chart_paired_show_lines) !== false;
  normalized.chart_likert_enabled = (/** @type {any} */ (normalized).chart_likert_enabled) === true;
  normalized.chart_x_label_wrap = Number.isFinite(Number((/** @type {any} */ (normalized).chart_x_label_wrap)))
    ? Number((/** @type {any} */ (normalized).chart_x_label_wrap)) : 3;
  normalized.chart_include_zero = (/** @type {any} */ (normalized).chart_include_zero) !== false;
  // Static by default: charts render without hover crosshair / zoom / pan. Opt-in via
  // `chart_interactive: true` surfaces Plotly's native interactive gestures.
  /** @type {any} */ (normalized).chart_interactive = (/** @type {any} */ (normalized).chart_interactive) === true;
  // Title visibility toggles: main title HIDDEN by default (redundant with axis titles
  // in most cases), both axis titles VISIBLE by default (they now carry actual info —
  // "Count" / "Value" / var labels — thanks to the consolidation feature).
  /** @type {any} */ (normalized).chart_show_title = (/** @type {any} */ (normalized).chart_show_title) === true;
  /** @type {any} */ (normalized).chart_show_xaxis_title = (/** @type {any} */ (normalized).chart_show_xaxis_title) !== false;
  /** @type {any} */ (normalized).chart_show_yaxis_title = (/** @type {any} */ (normalized).chart_show_yaxis_title) !== false;
  // Legend styling (multi-trace charts: q×q, paired_q, likert). Defaults chosen to
  // fix the "legend consumes half the plot width" issue: top-oriented legend recovers
  // horizontal space; wrap=2 keeps 3+ word labels compact.
  /** @type {any} */ (normalized).chart_legend_position = ['top', 'right', 'bottom']
    .includes((/** @type {any} */ (normalized).chart_legend_position))
    ? (/** @type {any} */ (normalized).chart_legend_position)
    : 'top';
  /** @type {any} */ (normalized).chart_show_legend_title = (/** @type {any} */ (normalized).chart_show_legend_title) !== false;
  // Independent wraps for legend title (default 4 — title has horizontal room in top/
  // bottom orientation) vs. entries (default 2 — trace pills stack tightly).
  /** @type {any} */ (normalized).chart_legend_title_wrap = Number.isFinite(Number((/** @type {any} */ (normalized).chart_legend_title_wrap)))
    ? Number((/** @type {any} */ (normalized).chart_legend_title_wrap))
    : 4;
  /** @type {any} */ (normalized).chart_legend_labels_wrap = Number.isFinite(Number((/** @type {any} */ (normalized).chart_legend_labels_wrap)))
    ? Number((/** @type {any} */ (normalized).chart_legend_labels_wrap))
    : 2;
  normalized.missing_label = normalized.missing_label ?? getDefaultMissingLabel(lang);

  const residuals = normalized.residual_symbols ?? {};
  normalized.residual_symbols = {
    greater: residuals.greater ?? translate('table.legends.residualGreaterSymbol', lang),
    lower: residuals.lower ?? translate('table.legends.residualLowerSymbol', lang)
  };

  const binaryLabels = getBinaryLabels(lang);
  normalized.yes_label = normalized.yes_label ?? binaryLabels.yes;
  normalized.no_label = normalized.no_label ?? binaryLabels.no;

  const minCount = Number(normalized.binary_min_count);
  normalized.binary_min_count = Number.isFinite(minCount) && minCount > 0 ? Math.floor(minCount) : 1;

  return normalized;
};

/**
 * Replace col_label in a list of column payloads with the label from the source database.
 * Accepts either JSON strings or plain objects and returns JSON strings (so Bubble can store them).
 * @param {Array<string|Record<string, any>>} columnPayloads
 * @param {Record<string,{columns:any[]}>} dbs
 * @returns {string[]} Updated payloads as JSON strings
 */
ns.updateColumnLabelsFromDb = function (columnPayloads, dbs) {
  if (!Array.isArray(columnPayloads)) return [];
  return columnPayloads.map((entry) => {
    let col;
    if (typeof entry === 'string') {
      try { col = JSON.parse(entry); } catch { return null; }
    } else if (entry && typeof entry === 'object') {
      col = { ...entry };
    } else {
      return null;
    }
    if (!col.database_id || !col.col_hash) return null;
    const db = dbs?.[col.database_id];
    if (!db) return null;
    const baseCol = ns.getColumn(db, col.col_hash);
    if (!baseCol) return null;
    const hasVariantIndex = col.col_var_index !== null && col.col_var_index !== undefined;
    const variant = hasVariantIndex && Array.isArray(baseCol.col_vars) ? baseCol.col_vars[col.col_var_index] : null;
    const label = variant?.var_label || baseCol.col_label || col.col_label || '';
    return JSON.stringify({ ...col, col_label: label });
  }).filter(Boolean);
};

const normalizeHeaderForMatch = (label) => String(label ?? '')
  .toLowerCase()
  .replace(/[^a-z0-9]+/g, '')
  .trim();

/**
 * Suggest mappings between new columns and existing columns for a Bubble RG.
 * Returns objects ready to JSON.stringify for the RG data source.
 * @param {{columns?: any[]}} oldDb
 * @param {{columns?: any[]}} newDb
 * @param {Array<string|{new_hash:string,new_label?:string,new_type?:string,choice?:string,suggested_choice?:string}>} [existingMappings]
 * @returns {{ mappings: string[], warnings: string[], errors: string[] }}
 */
ns.buildColumnMappingSuggestions = function (oldDb, newDb, existingMappings = null) {
  const oldCols = Array.isArray(oldDb?.columns) ? oldDb.columns : [];
  const newCols = Array.isArray(newDb?.columns) ? newDb.columns : [];
  const warnings = [];
  const errors = [];
  const lang = normalizeLanguage(newDb?.lang ?? oldDb?.lang);
  const oldByHash = new Map(oldCols.map(c => [c.col_hash, c]));
  const oldByNorm = new Map();
  oldCols.forEach((col) => {
    const norm = normalizeHeaderForMatch(col.col_label ?? col.col_name ?? col.col_hash ?? '');
    if (!norm) return;
    if (!oldByNorm.has(norm)) oldByNorm.set(norm, []);
    oldByNorm.get(norm).push(col);
  });

  const existingMap = new Map(
    (Array.isArray(existingMappings) ? existingMappings : []).map((m) => {
      if (typeof m === 'string') {
        try { m = JSON.parse(m); } catch { return null; }
      }
      if (!m || !m.new_hash) return null;
      return [m.new_hash, m.choice ?? m.suggested_choice];
    }).filter(Boolean)
  );

  const mappings = newCols.map((col) => {
    const norm = normalizeHeaderForMatch(col.col_label ?? col.col_name ?? col.col_hash ?? '');
    let suggested_choice = 'NEW';
    const hasManual = existingMap.has(col.col_hash);
    const manualChoice = hasManual ? existingMap.get(col.col_hash) : undefined;

    if (hasManual) {
      suggested_choice = manualChoice ?? '';
      if (manualChoice && manualChoice !== 'NEW' && manualChoice !== 'IGNORE' && !oldByHash.has(manualChoice)) {
        errors.push(translate('mapping.invalid', lang, { label: col.col_label ?? col.col_name ?? col.col_hash }));
      }
    } else if (oldByHash.has(col.col_hash)) {
      // Same hash exists in old DB; prefer it directly
      suggested_choice = col.col_hash;
    } else if (norm && oldByNorm.has(norm)) {
      const candidates = oldByNorm.get(norm);
      if (candidates.length === 1) {
        suggested_choice = candidates[0].col_hash;
      } else {
        errors.push(translate('mapping.multiple', lang, { label: col.col_label ?? col.col_name ?? col.col_hash }));
      }
    } else {
      warnings.push(translate('mapping.nomatch', lang, { label: col.col_label ?? col.col_name ?? col.col_hash }));
    }
    return JSON.stringify({
      new_hash: col.col_hash,
      new_label: col.col_label ?? col.col_name ?? col.col_hash,
      new_type: col.col_type ?? 'q',
      suggested_choice
    });
  });

  const mappedOld = new Set(
    mappings.map((m) => {
      try { m = JSON.parse(m); } catch { return null; }
      const choice = m.choice ?? m.suggested_choice;
      return choice && choice !== 'NEW' && choice !== 'IGNORE' ? choice : null;
    }).filter(Boolean)
  );
  const choiceCounts = new Map();
  mappings.forEach((m) => {
    try { m = JSON.parse(m); } catch { return; }
    const choice = m.choice ?? m.suggested_choice;
    if (!choice || choice === 'NEW' || choice === 'IGNORE') return;
    choiceCounts.set(choice, (choiceCounts.get(choice) || 0) + 1);
  });
  choiceCounts.forEach((count, choice) => {
    if (count > 1) {
      const label = (oldByHash.get(choice)?.col_label ?? oldByHash.get(choice)?.col_name ?? choice);
      errors.push(translate('mapping.multiple', lang, { label }));
    }
  });

  oldCols.forEach((col) => {
    if (!mappedOld.has(col.col_hash)) {
      warnings.push(translate('mapping.old_dropped', lang, { label: col.col_label ?? col.col_name ?? col.col_hash }));
    }
  });

  return { mappings, warnings, errors };
};

/**
 * Apply confirmed mappings to produce a new DB payload.
 * @param {{columns?: any[]}} oldDb
 * @param {{columns?: any[]}} newDb
 * @param {Array<string|{new_hash:string,new_label:string,choice:string}>} mappingEntries
 * @returns {Record<string, any>}
 */
ns.applyColumnMappings = function (oldDb, newDb, mappingEntries) {
  const oldCols = Array.isArray(oldDb?.columns) ? oldDb.columns : [];
  const newCols = Array.isArray(newDb?.columns) ? newDb.columns : [];
  const oldByHash = new Map(oldCols.map(c => [c.col_hash, c]));
  const mappingObjs = Array.isArray(mappingEntries) ? mappingEntries.map((m) => {
    if (typeof m === 'string') {
      try { return JSON.parse(m); } catch { return null; }
    }
    return m;
  }).filter(Boolean) : [];

  const choiceByNewHash = new Map(mappingObjs.map(m => [m.new_hash, m.choice ?? m.suggested_choice ?? 'NEW']));
  const result = [];
  const namesMatch = (a, b) => (a ?? '').trim().toLowerCase() === (b ?? '').trim().toLowerCase();

  newCols.forEach((col, idx) => {
    const choice = choiceByNewHash.get(col.col_hash) ?? 'NEW';
    if (choice === 'IGNORE') return;
    if (choice !== 'NEW' && oldByHash.has(choice)) {
      const oldCol = oldByHash.get(choice);
      const mergedMeta = (oldCol.meta || col.meta)
        ? { ...(oldCol.meta || {}), ...(col.meta || {}) }
        : undefined;
      // Preserve old processing config (new columns from parseColumns have empty processing)
      if (mergedMeta && oldCol.meta?.processing && Object.keys(oldCol.meta.processing).length > 0) {
        mergedMeta.processing = { ...(oldCol.meta.processing), ...(col.meta?.processing && Object.keys(col.meta.processing).length > 0 ? col.meta.processing : {}) };
      }
      const merged = { ...col, col_hash: oldCol.col_hash, ...(mergedMeta ? { meta: mergedMeta } : {}) };
      // Preserve in-app customized labels when the column name did not change; otherwise prefer the new label from the file
      const useOldLabel = namesMatch(col.col_name, oldCol.col_name);
      merged.col_label = useOldLabel
        ? (oldCol.col_label ?? col.col_label)
        : (col.col_label ?? oldCol.col_label);
      if (Array.isArray(oldCol.col_vars) && oldCol.col_vars.length) {
        // Rebuild variants when possible using stored recipes.
        // Base variant is pointer-style (no col_values/col_type/col_sep) — readers fall back to the column.
        const baseLabel = oldCol.col_vars[0]?.var_label ?? (col.col_label ?? col.col_name ?? 'Original');
        const baseMeta = oldCol.col_vars[0]?.meta?.kind === 'original' ? oldCol.col_vars[0].meta : { kind: 'original' };
        const baseVariant = {
          var_label: baseLabel,
          meta: baseMeta
        };
        const rebuilt = [baseVariant];
        const tempBase = { ...merged, col_vars: rebuilt };
        oldCol.col_vars.slice(1).forEach((v) => {
          const recipe = v?.meta?.recipe;
          if (recipe) {
            try {
              const newVar = variants.createVariant(tempBase, recipe);
              if (v?.var_label) {
                newVar.var_label = v.var_label;
              }
              rebuilt.push(newVar);
              tempBase.col_vars = rebuilt;
            } catch {
              rebuilt.push(v);
            }
          } else {
            rebuilt.push(v);
          }
        });
        merged.col_vars = rebuilt;
      }
      result.push(merged);
    } else {
      result.push(col);
    }
  });

  result.forEach((col, i) => { col.col_index = i + 1; });
  // meta.replacements is preserved through the merge above (oldCol.meta spread)
  // and re-applied lazily at read-time via factors.resolveColumn — no destructive replay needed.
  const resultMeta = { ...(oldDb?.meta || {}), ...(newDb?.meta || {}) };
  const merged = { ...newDb, columns: result, meta: resultMeta };
  snapshots.refreshDatabaseHashes(merged);
  return merged;
};

/**
 * Recode a column to a new `col_type` and/or `col_sep`.
 *
 * Pipeline:
 *   1. Decode the column using its CURRENT `col_type` / `col_sep`
 *   2. Apply the new type/separator (inferring `col_sep` for `'l'` when omitted)
 *   3. Re-encode raw values via `factors.makeColumn`
 *   4. Migrate `meta`: keep `replacements`, `excluded_values`, `na_action`, `na_label`;
 *      drop q-only fields (`sort_mode`, `custom_order`, `top_n`, `top_n_label`) when leaving `'q'`
 *   5. Rebuild `col_vars` (base variant adopts new shape; derived variants re-run their stored recipe)
 *
 * Returns a NEW column object; the input is never mutated.
 *
 * @param {{col_type?: 'q'|'n'|'l', col_sep?: string, col_values?: any, raw_values?: string[], col_vars?: any[], meta?: any, col_label?: string, col_name?: string, [k:string]: any}} column Source column object.
 * @param {{col_type?: 'q'|'n'|'l', col_sep?: string}} [changes]
 * @returns {Record<string, any>} New column object with re-encoded `col_values` and migrated metadata.
 */
ns.recodeColumn = function (column, changes = {}) {
  if (!column || typeof column !== 'object') return column;

  const oldType = column.col_type ?? 'q';
  const rawValues = factors.decodeColumn(column);

  const nextType = changes.col_type ?? oldType;
  let nextSep = changes.col_sep !== undefined ? changes.col_sep : column.col_sep;
  if (nextType === 'l') {
    if (!nextSep) nextSep = factors.inferColSep(rawValues) || ';';
  } else {
    nextSep = '';
  }

  const rebuilt = factors.makeColumn(rawValues, {
    col_type: nextType,
    col_sep: nextSep,
    includeBaseVariant: false,
    encode: true
  });

  const { col_vars: _ignored, col_values: __ignored, col_type: ___ignored, col_sep: ____ignored, meta: oldMeta, ...rest } = column;
  /** @type {Record<string, any>} */
  const nextColumn = {
    ...rest,
    col_type: rebuilt.col_type,
    col_sep: rebuilt.col_sep,
    col_values: rebuilt.col_values
  };

  if (oldMeta && typeof oldMeta === 'object') {
    const nextMeta = { ...oldMeta };
    if (oldMeta.processing && typeof oldMeta.processing === 'object') {
      const proc = { ...oldMeta.processing };
      if (nextType !== 'q') {
        delete proc.sort_mode;
        delete proc.custom_order;
        delete proc.top_n;
        delete proc.top_n_label;
      }
      nextMeta.processing = proc;
    }
    nextColumn.meta = nextMeta;
  }

  if (Array.isArray(column.col_vars) && column.col_vars.length > 0) {
    const baseLabel = column.col_vars[0]?.var_label
      ?? nextColumn.col_label
      ?? nextColumn.col_name
      ?? 'Original';
    const baseMeta = column.col_vars[0]?.meta?.kind === 'original'
      ? column.col_vars[0].meta
      : { kind: 'original' };
    // Pointer-style base variant (no col_values/col_type/col_sep) — readers use the column.
    const baseVariant = {
      var_label: baseLabel,
      meta: baseMeta
    };
    /** @type {Object[]} */
    const rebuiltVariants = [baseVariant];
    /** @type {string[]} */
    const warnings = [];
    let scratchBase = { ...nextColumn, col_vars: rebuiltVariants };
    column.col_vars.slice(1).forEach((/** @type {any} */ v) => {
      const recipe = v?.meta?.recipe;
      if (!recipe) {
        warnings.push(`Variant "${v?.var_label ?? 'unnamed'}" dropped: no recipe to replay against the new column shape.`);
        return;
      }
      try {
        const newVar = variants.createVariant(scratchBase, recipe);
        if (v?.var_label) newVar.var_label = v.var_label;
        rebuiltVariants.push(newVar);
        scratchBase = { ...scratchBase, col_vars: rebuiltVariants };
      } catch (/** @type {any} */ err) {
        warnings.push(`Variant "${v?.var_label ?? 'unnamed'}" dropped: recipe failed (${err?.message || err}).`);
      }
    });
    nextColumn.col_vars = rebuiltVariants;
    if (warnings.length > 0) {
      const meta = nextColumn.meta ? { ...nextColumn.meta } : {};
      meta.warnings = [...(Array.isArray(meta.warnings) ? meta.warnings : []), ...warnings];
      nextColumn.meta = meta;
    }
  }

  return nextColumn;
};

/**
 * Section header for a cell whose list side was expanded into per-item entries.
 *
 * `combineAnalysisAsSingleTable` renders `predictor ?? response`, so when BOTH axes carry
 * distinguishing information the header has to name both — otherwise every item comes out under the
 * same title, and with several predictors the sections become indistinguishable. Same reasoning as
 * the `n × n` pair-wise label at the tail of `summarizePredictors`.
 *
 * `label_list_with_column` governs the whole decoration, not just the list prefix: turn it off and
 * the header falls back to the bare item, for when the context is obvious to the reader. The item
 * label itself already honours the same option inside `summarize_*`.
 *
 * @param {string|null|undefined} contextLabel The opposite axis (the non-expanded column).
 * @param {string} itemLabel The per-item label, already prefixed or not by the same option.
 * @param {boolean} includePrefix
 * @returns {string}
 */
const composeExpandedLabel = (contextLabel, itemLabel, includePrefix) =>
  includePrefix && contextLabel ? `${contextLabel} × ${itemLabel}` : itemLabel;

/**
 * Summarize each predictor optionally against a qualitative response.
 * @param {Column[]} columns
 * @param {Array<{col_hash:string,col_label:string}>} predictors
 * @param {Array<{col_hash:string,col_label:string}>} responses
 * @param {Array<Record<string, any>>} data
 * @param {Record<string,any>} options
 * @param {Set<string>} flagsUsed
 * @param {Record<string,Function>=} formatFns
 * @returns {Array<{ predictor: string, response?: string|null, predictor_type: string, response_type?: string|null, table: TableLike }>}
 */
ns.summarizePredictors = function (columns, predictors, responses, data, options, flagsUsed, formatFns = {}) {
  const response = responses.length > 0 ? responses[0] : null;
  const responseCol = response
    ? columns.find(c => c.col_hash === response.col_hash && c.col_var_index === (response.col_var_index ?? null))
      || columns.find(c => c.col_hash === response.col_hash)
    : null;
  const responseType = responseCol?.col_type || null; const responseVals = responseCol?.raw_values || null;
  const lang = normalizeLanguage(options?.lang);

  // Profile B: no predictors + multiple responses → paired analysis across momentos.
  if (predictors.length === 0 && responses.length >= 1) {
    const pairedEntry = ns.summarizePaired(columns, responses, options, flagsUsed, lang);
    return pairedEntry ? [pairedEntry] : [];
  }

  // Likert eligibility (Profile A data shape only — mode + opt-in gated separately below).
  // Emit `has_likert_eligible` whenever the data supports a Likert chart: ≥2 predictors,
  // no response, every predictor is `q`, and levels intersect in ≥2 values. Kept
  // independent of `options.mode` and `options.chart_likert_enabled` so Panel_element_options
  // can gate the `chart_likert_enabled` toggle visibility precisely.
  /** @type {{likertCols:any[], shared:string[]}|null} */
  let likertEligibility = null;
  if (predictors.length >= 2 && responses.length === 0) {
    const likertCols = predictors.map((/** @type {any} */ p) => {
      const col = columns.find(c => c.col_hash === p.col_hash && c.col_var_index === (p.col_var_index ?? null))
        || columns.find(c => c.col_hash === p.col_hash);
      return col ? { pred: p, col } : null;
    }).filter(Boolean);
    const allQ = likertCols.length === predictors.length
      && likertCols.every((/** @type {any} */ c) => c.col?.col_type === 'q');
    if (allQ) {
      /** @type {Set<string>[]} */
      const levelSets = likertCols.map((/** @type {any} */ c) => new Set(
        (c.col.raw_values || []).map((/** @type {any} */ v) => String(v ?? '').trim()).filter(Boolean)
      ));
      const shared = levelSets.length > 0
        ? [...levelSets[0]].filter((l) => levelSets.every((s) => s.has(l)))
        : [];
      if (shared.length >= 2) {
        flagsUsed.add('has_likert_eligible');
        likertEligibility = { likertCols, shared };
      }
    }
  }

  // Likert short-circuit dispatch (chart mode + explicit opt-in): reuse the eligibility
  // computed above. If chart_likert returns null defensively, fall through to the
  // per-predictor path — eligibility already guarantees ≥2 shared levels today, so this
  // is dead-code insurance rather than a real fallback.
  if (likertEligibility && options?.mode === 'chart' && options?.chart_likert_enabled) {
    const chart = charts.chart_likert(
      likertEligibility.likertCols.map((/** @type {any} */ c) => ({ label: c.pred.col_label, values: c.col.raw_values || [] })),
      options
    );
    if (chart) {
      flagsUsed.add('has_q');
      return [/** @type {any} */ ({
        predictor: predictors.map((/** @type {any} */ p) => p.col_label).join(' / '),
        response: null,
        predictor_type: 'q',
        response_type: null,
        chart
      })];
    }
  }

  return predictors.map(pred => {
    const predictorCol = columns.find(c => c.col_hash === pred.col_hash && c.col_var_index === (pred.col_var_index ?? null))
      || columns.find(c => c.col_hash === pred.col_hash);
    if (!predictorCol) return null;
    const predictorVals = predictorCol.raw_values; const predictorType = predictorCol.col_type; const predictorSep = predictorCol.col_sep || ';'; const formatFn = formatFns[pred.col_label] || null;
    let table;
    /** @type {{type:string, spec:any}|null|undefined} */
    let chart;
    if (!response) {
      if (predictorType === 'q') {
        flagsUsed.add('has_q');
        if (options?.mode === 'chart') {
          chart = charts.chart_q(predictorVals ?? [], options, { varLabel: pred.col_label, labels: predictorCol.col_values?.labels ?? null });
        } else {
          table = ns.summarize_q(predictorVals, formatFn, options, { labels: predictorCol.col_values?.labels ?? null });
        }
      } else if (predictorType === 'l') {
        flagsUsed.add('has_l');
        if (options?.mode === 'chart') {
          chart = charts.chart_l(predictorVals ?? [], predictorSep, options, { varLabel: pred.col_label });
        } else {
          table = ns.summarize_l(predictorVals, predictorSep, formatFn, options);
        }
      } else if (predictorType === 'n') {
        flagsUsed.add('has_n');
        if (options?.mode === 'chart') {
          chart = charts.chart_n(predictorVals ?? [], options, { varLabel: pred.col_label });
        } else {
          table = numeric.summarize_n(predictorVals, formatFn, options);
        }
      }
    } else {
      if (predictorType === 'q' && responseType === 'q') {
        flagsUsed.add('has_qq');
        if (options?.mode === 'chart') {
          chart = charts.chart_q_q(predictorVals ?? [], responseVals ?? [], options, {
            predictorLabel: pred.col_label,
            responseLabel: response?.col_label || '',
            predictorLabels: predictorCol.col_values?.labels ?? null,
            responseLabels: responseCol.col_values?.labels ?? null
          });
        } else {
          const labelOptions = { rowLabels: predictorCol.col_values?.labels ?? null, colLabels: responseCol.col_values?.labels ?? null };
          table = contingency.summarize_q_q(predictorVals, responseVals, formatFn, options, labelOptions);
        }
      } else if (predictorType === 'n' && responseType === 'q') {
        flagsUsed.add('has_nq');
        if (options?.mode === 'chart') {
          chart = charts.chart_n_q(predictorVals ?? [], responseVals ?? [], options, {
            numericLabel: pred.col_label,
            groupLabel: response?.col_label || '',
            groupLabels: responseCol?.col_values?.labels ?? null
          });
        } else {
          const nqOptions = { ...options, responseLabels: responseCol?.col_values?.labels ?? null };
          table = numeric.summarize_n_q(predictorVals, responseVals, formatFn, flagsUsed, nqOptions);
        }
      } else if (predictorType === 'l' && responseType === 'q') {
        const includePrefix = options?.label_list_with_column ?? true;
        flagsUsed.add('has_lq');
        if (options?.mode === 'chart') {
          const chartSummaries = charts.chart_l_q(predictorVals ?? [], responseVals ?? [], options, {
            separator: predictorSep,
            predictorLabel: pred.col_label,
            responseLabel: response?.col_label || null,
            responseLabels: responseCol?.col_values?.labels ?? null,
            includePrefix
          }).map((/** @type {any} */ entry) => /** @type {any} */ ({
            predictor: entry.display_label,
            response: entry.response_label,
            predictor_type: 'q',
            response_type: responseType,
            chart: entry.chart
          }));
          return chartSummaries;
        }
        const summaries = ns.summarize_l_q(predictorVals, responseVals, formatFn, options, {
          separator: predictorSep,
          predictorLabel: pred.col_label,
          responseLabel: response?.col_label || null,
          lang,
          includePrefix
        }).map(entry => ({
          predictor: entry.display_label,
          response: entry.response_label,
          predictor_type: 'q',
          response_type: responseType,
          table: entry.table
        }));
        return summaries;
      } else if (predictorType === 'q' && responseType === 'l') {
        const includePrefix = options?.label_list_with_column ?? true;
        const responseSep = responseCol?.col_sep || ';';
        flagsUsed.add('has_ql');
        if (options?.mode === 'chart') {
          const chartSummaries = charts.chart_q_l(predictorVals ?? [], responseVals ?? [], options, {
            separator: responseSep,
            predictorLabel: pred.col_label,
            predictorLabels: predictorCol.col_values?.labels ?? null,
            responseLabel: response?.col_label || null,
            includePrefix
          }).map((/** @type {any} */ entry) => /** @type {any} */ ({
            predictor: composeExpandedLabel(pred.col_label, entry.display_label, includePrefix),
            response: entry.display_label,
            predictor_type: 'q',
            response_type: 'q',
            chart: entry.chart
          }));
          return chartSummaries;
        }
        const summaries = ns.summarize_q_l(predictorVals, responseVals, formatFn, options, {
          separator: responseSep,
          predictorLabel: pred.col_label,
          responseLabel: response?.col_label || null,
          lang,
          includePrefix
        }).map((/** @type {any} */ entry) => ({
          predictor: composeExpandedLabel(pred.col_label, entry.display_label, includePrefix),
          response: entry.display_label,
          predictor_type: 'q',
          response_type: 'q',
          table: entry.table
        }));
        return summaries;
      } else if (predictorType === 'n' && responseType === 'n') {
        flagsUsed.add('has_nn');
        if (options?.mode === 'chart') {
          chart = charts.chart_n_n(predictorVals ?? [], responseVals ?? [], options, {
            predictorLabel: pred.col_label,
            responseLabel: response?.col_label || ''
          });
        } else {
          table = numeric.summarize_n_n(predictorVals ?? [], responseVals ?? [], formatFn, options);
        }
      } else if (predictorType === 'q' && responseType === 'n') {
        // Axis inversion: pass numeric response as the "predictor" arg and qualitative
        // predictor as the "response" arg. summarize_n_q's output naturally lays out
        // groups (from the qualitative) as rows and numeric stats as columns — the
        // layout we want when q is the predictor.
        flagsUsed.add('has_qn');
        if (options?.mode === 'chart') {
          chart = charts.chart_q_n(predictorVals ?? [], responseVals ?? [], options, {
            predictorLabel: pred.col_label,
            responseLabel: response?.col_label || '',
            predictorLabels: predictorCol.col_values?.labels ?? null
          });
        } else {
          const qnOptions = { ...options, responseLabels: predictorCol.col_values?.labels ?? null };
          table = numeric.summarize_n_q(responseVals ?? [], predictorVals ?? [], formatFn, flagsUsed, qnOptions);
        }
      } else if (predictorType === 'l' && responseType === 'l') {
        /** @type {string[]} */
        const predSubset = Array.isArray(/** @type {any} */ (pred).subset_items)
          ? /** @type {any} */ (pred).subset_items.filter(Boolean) : [];
        /** @type {string[]} */
        const respSubset = Array.isArray(/** @type {any} */ (response).subset_items)
          ? /** @type {any} */ (response).subset_items.filter(Boolean) : [];
        flagsUsed.add('has_ll');
        if (!predSubset.length || !respSubset.length) {
          // Warning case (subset missing) is identical in both modes — the renderer's
          // warning branch handles it. Stored as a table-shaped entry for backward parity.
          table = { warning: translate('warnings.llSubsetRequired', lang) };
        } else {
          const includePrefix = options?.label_list_with_column ?? true;
          if (options?.mode === 'chart') {
            const chartSummaries = charts.chart_l_l(predictorVals ?? [], responseVals ?? [], options, {
              predictorSep,
              responseSep: responseCol?.col_sep || ';',
              predictorLabel: pred.col_label,
              responseLabel: response?.col_label || null,
              predSubset,
              respSubset,
              includePrefix
            }).map((/** @type {any} */ entry) => /** @type {any} */ ({
              predictor: `${entry.display_predictor} × ${entry.display_response}`,
              response: entry.display_response,
              predictor_type: 'q',
              response_type: 'q',
              chart: entry.chart
            }));
            return chartSummaries;
          }
          const summaries = ns.summarize_l_l(predictorVals, responseVals, formatFn, options, {
            predictorSep,
            responseSep: responseCol?.col_sep || ';',
            predictorLabel: pred.col_label,
            responseLabel: response?.col_label || null,
            predSubset,
            respSubset,
            lang,
            includePrefix
          }).map((/** @type {any} */ entry) => ({
            predictor: `${entry.display_predictor} × ${entry.display_response}`,
            response: entry.display_response,
            predictor_type: 'q',
            response_type: 'q',
            table: entry.table
          }));
          return summaries;
        }
      } else if (predictorType === 'l' && responseType === 'n') {
        const includePrefix = options?.label_list_with_column ?? true;
        flagsUsed.add('has_ln');
        if (options?.mode === 'chart') {
          const chartSummaries = charts.chart_l_n(predictorVals ?? [], responseVals ?? [], options, {
            separator: predictorSep,
            predictorLabel: pred.col_label,
            responseLabel: response?.col_label || null,
            includePrefix
          }).map((/** @type {any} */ entry) => /** @type {any} */ ({
            predictor: entry.display_label,
            response: entry.response_label,
            predictor_type: 'q',
            response_type: 'n',
            chart: entry.chart
          }));
          return chartSummaries;
        }
        const summaries = ns.summarize_l_n(predictorVals, responseVals, formatFn, flagsUsed, options, {
          separator: predictorSep,
          predictorLabel: pred.col_label,
          responseLabel: response?.col_label || null,
          lang,
          includePrefix
        }).map((/** @type {any} */ entry) => ({
          predictor: entry.display_label,
          response: entry.response_label,
          predictor_type: 'q',
          response_type: 'n',
          table: entry.table
        }));
        return summaries;
      } else if (predictorType === 'n' && responseType === 'l') {
        // Axis inversion of l × n: the list RESPONSE is expanded into binary presence items and
        // the numeric predictor is compared across the two groups each item forms. Entries are
        // labelled exactly like l × n (item as `predictor`) so the section header stays
        // identifiable — `combineAnalysisAsSingleTable` renders `predictor ?? response`.
        const includePrefix = options?.label_list_with_column ?? true;
        const responseSep = responseCol?.col_sep || ';';
        flagsUsed.add('has_nl');
        const nlMeta = {
          separator: responseSep,
          predictorLabel: pred.col_label,
          responseLabel: response?.col_label || null,
          includePrefix
        };
        if (options?.mode === 'chart') {
          const chartSummaries = charts.chart_n_l(predictorVals ?? [], responseVals ?? [], options, nlMeta)
            .map((/** @type {any} */ entry) => /** @type {any} */ ({
              predictor: composeExpandedLabel(pred.col_label, entry.display_label, includePrefix),
              response: entry.response_label,
              predictor_type: 'q',
              response_type: 'n',
              chart: entry.chart
            }));
          return chartSummaries;
        }
        const summaries = ns.summarize_n_l(predictorVals, responseVals, formatFn, flagsUsed, options, { ...nlMeta, lang })
          .map((/** @type {any} */ entry) => ({
            predictor: composeExpandedLabel(pred.col_label, entry.display_label, includePrefix),
            response: entry.response_label,
            predictor_type: 'q',
            response_type: 'n',
            table: entry.table
          }));
        return summaries;
      }
    }
    if (table?.used_resid_greater || table?.used_resid_lower) flagsUsed.add('has_residuals');
    // n × n is a pair-wise correlation; the header label needs both axes to be meaningful.
    const finalPredictorLabel = (predictorType === 'n' && responseType === 'n' && response?.col_label)
      ? `${pred.col_label} × ${response.col_label}`
      : pred.col_label;
    // Chart mode: emit `chart` instead of `table` when present.
    if (chart) {
      return /** @type {any} */ ({ predictor: finalPredictorLabel, response: response?.col_label || null, predictor_type: predictorType, response_type: responseType, chart });
    }
    return { predictor: finalPredictorLabel, response: response?.col_label || null, predictor_type: predictorType, response_type: responseType, table };
  }).filter(Boolean).flat();
};

/**
 * Locate a Profile C response inside one database.
 *
 * `col_hash` is the MD5 of the column NAME, so matching by hash IS matching by exact name. When the
 * same variable was spelled differently across uploads (`sharedoutcome` vs `SharedOutcome`) the
 * hashes differ, and renaming `col_label` in the app cannot repair it — the hash is baked at upload
 * from the spreadsheet header. So fall back to the normalized label, the same key
 * `buildColumnMappingSuggestions` matches on. That is not a looser rule than the hash: it is the
 * very same "same column name = same variable" semantic, made insensitive to case and punctuation.
 *
 * Only a UNIQUE match counts — two candidates are ambiguous and reported as not found, so the
 * caller emits its normal "missing in database X" warning rather than guessing.
 *
 * @param {{columns?: Column[]}|null|undefined} db
 * @param {{col_hash?: string, col_label?: string}} response
 * @returns {any|null}
 */
const findResponseInDb = (db, response) => {
  if (!db || !Array.isArray(db.columns)) return null;
  const byHash = ns.getColumn(db, /** @type {string} */ (response?.col_hash));
  if (byHash) return byHash;
  const target = normalizeHeaderForMatch(response?.col_label);
  if (!target) return null;
  const matches = db.columns.filter((/** @type {any} */ col) =>
    normalizeHeaderForMatch(col?.col_label ?? col?.col_name) === target);
  return matches.length === 1 ? matches[0] : null;
};

/**
 * Normalized category keys of a resolved column, for comparing level identity across databases.
 * Compared through `normalizeHeaderForMatch` so "Yes"/"yes" is not reported as a divergence.
 * @param {{columns?: Column[]}} db
 * @param {any} column
 * @returns {Set<string>}
 */
const responseLevelKeys = (db, column) => {
  const resolved = factors.resolveVariable(db, column.col_hash, null);
  const colType = resolved?.colType ?? 'q';
  const colSep = resolved?.colSep ?? ';';
  /** @type {Set<string>} */
  const keys = new Set();
  for (const value of resolved?.values ?? []) {
    if (factors.isMissingValue(value, colType, colSep)) continue;
    const items = colType === 'l'
      ? String(value).split(colSep).map((/** @type {string} */ s) => s.trim()).filter(Boolean)
      : [String(value).trim()];
    for (const item of items) {
      const key = normalizeHeaderForMatch(item);
      if (key) keys.add(key);
    }
  }
  return keys;
};

/**
 * End-to-end analysis from Bubble element inputs to combined analysis object.
 * @param {string[]} elementPredictors JSON strings
 * @param {string[]} elementResponses JSON strings
 * @param {Record<string,{columns:Column[]}>} dbs databases by id
 * @param {Record<string,any>} options
 * @returns {{ result: CombinedAnalysis, flags: string[] }}
 */
ns.runAnalysis = function (elementPredictors, elementResponses, dbs, options) {
  const mergedOptions = ns.getDefaultAnalysisOptions(options);
  const predictors = elementPredictors.map(JSON.parse); const responses = elementResponses.map(JSON.parse); const flagsUsed = new Set();
  const lang = mergedOptions.lang;

  // Multi-DB validation + D2 broadcast (Profile C only). Two separate concerns, both gated on
  // "there is a response and at least one predictor":
  //
  //   1. The response must exist in EVERY database the predictors come from — including the
  //      single-database case. Rows are paired positionally downstream, so analysing a predictor
  //      from database A against a response from database B silently correlates unrelated records
  //      (and the two tables need not even have the same row count).
  //   2. Only when the predictors actually span MORE than one database does the analysis
  //      broadcast: it runs per-DB and concatenates the results.
  //
  // Profile A (descriptive only) works across DBs naturally via per-predictor resolution, and
  // Profile B (paired, no predictors) is validated separately by `summarizePaired`.
  const predictorDbIds = new Set(predictors.map((/** @type {any} */ p) => p.database_id));
  if (predictors.length > 0 && responses.length > 0) {
    const response = responses[0];
    /** @type {string[]} */
    const missingDbs = [];
    /** @type {Map<string, any>} Database id → the column that database contributes as the response. */
    const responseColByDb = new Map();
    for (const dbId of predictorDbIds) {
      const db = dbs[/** @type {string} */ (dbId)];
      const responseCol = db ? findResponseInDb(db, response) : null;
      if (!responseCol) missingDbs.push(/** @type {string} */ (dbId));
      else responseColByDb.set(/** @type {string} */ (dbId), responseCol);
    }
    // Databases that can actually contribute an analysis. Those missing the response are dropped
    // rather than aborting the whole Element: a predictor whose own database holds the response is
    // still perfectly analysable, and losing it would hide valid work behind an unrelated gap.
    const contributingDbIds = [...predictorDbIds].filter(dbId => responseColByDb.has(/** @type {string} */ (dbId)));

    /** @type {any[]} Non-blocking entries prepended to the analysis list. */
    const notices = [];
    if (missingDbs.length > 0) {
      flagsUsed.add('has_multi_db_missing_response');
      notices.push({
        predictor: null,
        response: response.col_label || null,
        predictor_type: null,
        response_type: null,
        table: { warning: translate('warnings.multiDbMissingResponse', lang, {
          label: response.col_label || response.col_hash
        }) }
      });
    }
    if (contributingDbIds.length === 0) {
      return /** @type {any} */ ({
        result: { analysis: notices, test_legend: [], lang },
        flags: Array.from(flagsUsed)
      });
    }
    // A shared name does not guarantee shared categories. Flag the divergence so the UI can warn;
    // the analyses themselves are left alone, each being valid within its own database. Numeric
    // responses are skipped: their distinct values are data, not categories.
    if (contributingDbIds.length > 1) {
      const isCategorical = contributingDbIds.every(dbId => (responseColByDb.get(dbId)?.col_type ?? 'q') !== 'n');
      if (isCategorical) {
        const levelSets = contributingDbIds.map(dbId => responseLevelKeys(dbs[/** @type {string} */ (dbId)], responseColByDb.get(dbId)));
        const reference = levelSets[0];
        const diverges = levelSets.some(set => set.size !== reference.size || [...set].some(key => !reference.has(key)));
        if (diverges) flagsUsed.add('has_multi_db_level_mismatch');
      }
    }
    // Per-database run whenever more than one database contributes, or whenever some were dropped
    // (so the surviving analyses still reach the user with the notice riding along). A single
    // contributing database with nothing dropped falls through to the normal path below.
    if (contributingDbIds.length > 1 || missingDbs.length > 0) {
      // Only a genuine concatenation across databases counts as a broadcast.
      if (contributingDbIds.length > 1) flagsUsed.add('has_multi_db_broadcast');
      /** @type {any[]} */
      const aggregatedEntries = [...notices];
      for (const dbId of contributingDbIds) {
        const dbPredictors = predictors.filter((/** @type {any} */ p) => p.database_id === dbId);
        // Rebind BOTH fields: the match may have come from the normalized label, in which case
        // this database stores the column under a different hash.
        const dbResponse = { ...response, database_id: dbId, col_hash: responseColByDb.get(/** @type {string} */ (dbId)).col_hash };
        const subResult = ns.runAnalysis(
          dbPredictors.map((/** @type {any} */ p) => JSON.stringify(p)),
          [JSON.stringify(dbResponse)],
          dbs,
          options
        );
        subResult.flags.forEach((/** @type {string} */ f) => flagsUsed.add(f));
        aggregatedEntries.push(...subResult.result.analysis);
      }
      // Rebuild symbol map on combined methods so symbols are consistent across DBs.
      const allMethods = aggregatedEntries.map((r) => r.table?.test_used).filter(Boolean);
      const symbolMap = ns.generateTestSymbolMap(allMethods, mergedOptions);
      aggregatedEntries.forEach((r) => {
        if (r.table?.test_used) {
          r.table.test_symbol = symbolMap[r.table.test_used];
        }
      });
      const test_legend = Object.entries(symbolMap).map(([method, symbol]) => ({ method, symbol }));
      return /** @type {any} */ ({
        result: { analysis: aggregatedEntries, test_legend, lang },
        flags: Array.from(flagsUsed)
      });
    }
    // Single predictor database, response present in it. `col_hash` is the MD5 of the column NAME,
    // so it is unique only WITHIN a database: two uploads that both have a "Outcome" column share
    // the same hash. A response picked from another database therefore passes the check above while
    // still resolving against ITS OWN table — pairing unrelated rows. Rebind it to the predictors'
    // database, the same rewrite the broadcast performs per database.
    const soleDbId = /** @type {string} */ (contributingDbIds[0]);
    const soleResponseCol = responseColByDb.get(soleDbId);
    if (response.database_id !== soleDbId || response.col_hash !== soleResponseCol.col_hash) {
      responses[0] = { ...response, database_id: soleDbId, col_hash: soleResponseCol.col_hash };
    }
  }

  const columns = predictors.concat(responses).map(col => {
    // Read-time pipeline (variant lookup + meta.replacements + meta.processing) lives in
    // factors.resolveVariable; only the analysis-specific record shape is assembled here.
    const resolved = factors.resolveVariable(dbs[col.database_id], col.col_hash, col.col_var_index);
    if (!resolved) return null;
    return {
      col_hash: resolved.column.col_hash,
      // The signature's label wins: it carries the user's current edit from the UI.
      col_label: col.col_label || resolved.label,
      col_type: resolved.colType,
      col_sep: resolved.colSep,
      col_values: resolved.colValues,
      raw_values: resolved.values,
      col_var_index: resolved.varIndex,
      var_meta: resolved.variant?.meta ?? null
    };
  }).filter(Boolean);
  const rowwise = ns.getRowwiseData(columns);
  const result = ns.summarizePredictors(columns, predictors, responses, rowwise, mergedOptions, flagsUsed);
  const allMethods = result.map(r => r.table?.test_used).filter(Boolean);
  const symbolMap = ns.generateTestSymbolMap(allMethods, mergedOptions);
  result.forEach(r => { if (r.table?.test_used) { const method = r.table.test_used; r.table.test_symbol = symbolMap[method]; } });
  // Chart post-processing: axis-title visibility toggles + spec.config.staticPlot.
  // Chart builders always emit meaningful axis titles (Count/%/n(%) for bar-family,
  // "Value" for chart_n numeric axis, variable labels for scatter/individual-values).
  // Hiding a title just blanks its .text so Plotly reserves no space for it.
  const staticPlot = (/** @type {any} */ (mergedOptions).chart_interactive) !== true;
  const showXTitle = (/** @type {any} */ (mergedOptions).chart_show_xaxis_title) !== false;
  const showYTitle = (/** @type {any} */ (mergedOptions).chart_show_yaxis_title) !== false;
  // Reclaim ~25px of margin per hidden axis title (Plotly reserves that space in the
  // caller-set `margin.b` / `margin.l` regardless of whether the title text is empty).
  // Min clamps: 25px bottom (fits single-line tick text), 40px left (fits 4-5 digit
  // numeric ticks like "1000" or "100%"). Charts that don't set a title in the first
  // place (chart_n xaxis uses tick text, likert yaxis is empty, etc.) are skipped by
  // the `layout.<axis>?.title` guard — no margin change on them.
  const TITLE_MARGIN_RECLAIM = 25;
  const MIN_MARGIN_B = 25;
  const MIN_MARGIN_L = 40;
  result.forEach((/** @type {any} */ r) => {
    if (!r.chart?.spec) return;
    r.chart.spec.config = { ...(r.chart.spec.config || {}), staticPlot };
    const layout = r.chart.spec.layout || {};
    layout.margin = layout.margin || {};
    if (!showXTitle && layout.xaxis?.title) {
      layout.xaxis.title.text = '';
      if (typeof layout.margin.b === 'number') {
        layout.margin.b = Math.max(MIN_MARGIN_B, layout.margin.b - TITLE_MARGIN_RECLAIM);
      }
    }
    if (!showYTitle && layout.yaxis?.title) {
      layout.yaxis.title.text = '';
      if (typeof layout.margin.l === 'number') {
        layout.margin.l = Math.max(MIN_MARGIN_L, layout.margin.l - TITLE_MARGIN_RECLAIM);
      }
    }
  });
  const test_legend = Object.entries(symbolMap).map(([method, symbol]) => ({ method, symbol }));
  // `chart_options` bag on the result carries HTML-level chart display flags for
  // `exportCombinedAsChartHTML` to consume (currently: `show_title` gates the
  // <div class="statz-chart-title"> heading above each cell — warning cells always
  // keep their heading so the user can identify which analysis was rejected).
  /** @type {any} */
  const finalResult = { analysis: result, test_legend, lang };
  finalResult.chart_options = {
    show_title: (/** @type {any} */ (mergedOptions).chart_show_title) === true
  };
  return { result: finalResult, flags: Array.from(flagsUsed) };
};

/**
 * Produce a lightweight summary for a column or one of its variants.
 * Returns `"label: summary"` pairs by default or `{ label, summary }` objects when `structured` is true.
 * @param {Column} column
 * @param {number|null} [variantIndex]
 * @param {{ lang?: string, formatFn?: Function, maxRows?: number, structured?: boolean }} [options]
 * @returns {Array<Record<string, string>> | Array<{label:string, summary:string}>}
 */
ns.describeColumn = function (column, variantIndex = null, options = {}) {
  if (!column || typeof column !== 'object') return [];
  let baseColumn = column;
  if (!baseColumn.col_hash) {
    baseColumn = { ...column, col_hash: '__temp_col_hash__' };
  }
  const colHash = baseColumn.col_hash;
  const database = { columns: [baseColumn] };
  let resolved;
  try {
    // resolveVariable applies meta.replacements + meta.processing with a PER-FIELD fallback from
    // the variant to its parent column, so a variant declaring only `processing` still inherits the
    // column's `replacements`. (This used to be a whole-object fallback here, which blocked them.)
    resolved = factors.resolveVariable(database, colHash, variantIndex);
  } catch (error) {
    console.warn('describeColumn: failed to decode column values.', error);
    return [];
  }
  if (!resolved) return [];
  const values = Array.isArray(resolved.values) ? resolved.values : [];
  if (!values.length) return [];
  const colType = resolved.colType;
  const colSep = resolved.colSep;
  const structured = options?.structured === true;
  const lang = normalizeLanguage(options?.lang);
  const summaryOptions = { ...options, lang };
  delete summaryOptions.formatFn;
  delete summaryOptions.maxRows;
  delete summaryOptions.structured;
  const formatFn = options.formatFn ?? null;
  let table;
  try {
    if (colType === 'q') {
      // Post-resolution factor order (applyProcessing may have re-sorted or merged the levels).
      const labels = resolved.colValues?.labels ?? null;
      table = ns.summarize_q(values, formatFn, summaryOptions, { labels });
    } else if (colType === 'l') {
      table = ns.summarize_l(values, colSep, formatFn, summaryOptions);
    } else if (colType === 'n') {
      table = numeric.summarize_n(values, formatFn, summaryOptions);
    } else {
      return [];
    }
  } catch (error) {
    console.warn('describeColumn: failed to build summary.', error);
    return [];
  }
  const columns = Array.isArray(table?.columns) && table.columns.length > 0
    ? table.columns
    : (Array.isArray(table?.rows) && table.rows[0] ? Object.keys(table.rows[0]) : []);
  const rows = Array.isArray(table?.rows) ? table.rows : [];
  if (!columns.length || !rows.length) return [];
  const maxRowsValue = Number(options?.maxRows);
  const maxRows = Number.isFinite(maxRowsValue) && maxRowsValue > 0 ? Math.floor(maxRowsValue) : null;
  const slice = maxRows ? rows.slice(0, maxRows) : rows;
  const normalizeCell = (value) => {
    if (value === null || value === undefined) return '';
    if (typeof value === 'number' && !Number.isFinite(value)) return '';
    return String(value).trim();
  };
  return slice.map((row) => {
    const columnValues = {};
    columns.forEach((colName) => {
      if (Object.prototype.hasOwnProperty.call(row, colName)) {
        columnValues[String(colName)] = normalizeCell(row[colName]);
      }
    });
    const firstColumnName = String(columns[0] ?? '');
    const label = (columnValues[firstColumnName] ?? '').trim();
    const summary = columns.slice(1)
      .map((colName) => columnValues[String(colName)] ?? '')
      .filter((value) => value && value.trim())
      .join(' | ');
    if (!label && !summary) return null;
    if (structured) {
      return { label, summary };
    }
    const formatted = (() => {
      if (label && summary) return `${label}: ${summary}`;
      if (label) return label;
      if (summary) return summary;
      return '';
    })();
    return formatted ? formatted : null;
  }).filter(Boolean);
};

/**
 * Summarize every column (and its variants) in a parsed database payload.
 *
 * The `variants` array in each entry mirrors `col_vars` by default — including the
 * pointer-style base variant at index 0 whose `summary` is empty (since it has no own
 * data; the column-level `summary` already represents the base). Set
 * `includeBaseAsVariant: false` to skip the base and return only user-created variants
 * (indices ≥ 1) — useful when callers want a clean list of derived variants.
 *
 * @param {{columns?: Column[]}|null|undefined} database
 * @param {{ lang?: string, formatFn?: Function, maxRows?: number, structured?: boolean, includeDeleted?: boolean, includeBaseAsVariant?: boolean }} [options]
 * @returns {Array<{ label: string, type: string, summary: Array<any>, variants: Array<{ label: string, type: string, summary: Array<any> }> }>}
 */
ns.describeDataset = function (database, options = {}) {
  if (!database || !Array.isArray(database.columns)) return [];

  const includeDeleted = options.includeDeleted === true;
  // Default true for backward compatibility — current callers expect col_vars[0] in the list.
  const includeBaseAsVariant = options.includeBaseAsVariant !== false;
  const columns = includeDeleted
    ? database.columns
    : database.columns.filter((col) => !col.col_del);

  return columns.map((column) => {
    const label = column.col_label ?? column.col_name ?? column.col_hash ?? '';
    const type = column.col_type ?? 'q';
    const summary = ns.describeColumn(column, null, options);
    const variantEntries = Array.isArray(column.col_vars)
      ? (includeBaseAsVariant ? column.col_vars : column.col_vars.slice(1))
      : [];
    const variants = variantEntries.map((variant) => ({
      label: variant.var_label ?? label,
      type: variant.col_type ?? type,
      summary: ns.describeColumn(variant, null, options)
    }));

    return { label, type, summary, variants };
  });
};

/**
 * Reorder a JSON-string list by moving an item and renumbering the `order` field.
 *
 * Supported directions, mapped to array index movement (and natural vertical-list
 * orientation):
 *  - `'up'`     → one position towards the head (`idx - 1`).
 *  - `'down'`   → one position towards the tail (`idx + 1`).
 *  - `'top'`    → first position (`0`).
 *  - `'bottom'` → last position (`list.length - 1`).
 *
 * The helper returns the **original list unchanged** when:
 *  - `index` is invalid (NaN, negative, or out of bounds);
 *  - the resulting target index is the same as `index` (no-op);
 *  - `direction` is not one of the four supported values.
 *
 * Items with unparseable JSON are preserved as-is; only the surrounding items get
 * their `order` field renumbered.
 *
 * @param {string[]} list JSON strings with an "order" field
 * @param {number|string} index 0-based index of the item to move
 * @param {'up'|'down'|'top'|'bottom'} direction Move direction
 * @returns {string[]} Updated list with renumbered `order` fields, or the input unchanged
 */
ns.reorderVariableList = function (list, index, direction) {
  const copy = list.slice();
  const idx = parseInt(index, 10);
  if (!Array.isArray(copy) || Number.isNaN(idx) || idx < 0 || idx >= copy.length) return list;
  /** @type {number} */
  let targetIndex;
  switch (direction) {
    case 'up':     targetIndex = idx - 1; break;
    case 'down':   targetIndex = idx + 1; break;
    case 'top':    targetIndex = 0; break;
    case 'bottom': targetIndex = copy.length - 1; break;
    default: return list;
  }
  if (targetIndex < 0 || targetIndex >= copy.length || targetIndex === idx) return list;
  // Move (not swap): splice out, then re-insert at the target position. Equivalent to a
  // single-step swap when |targetIndex - idx| === 1; for top/bottom, splice shifts all
  // intermediate items correctly.
  const [moved] = copy.splice(idx, 1);
  copy.splice(targetIndex, 0, moved);
  const updated = copy.map((item, i) => {
    try {
      const obj = JSON.parse(item);
      obj.order = i + 1;
      return JSON.stringify(obj);
    } catch (e) {
      return item;
    }
  });
  return updated;
};

export default { ...ns, ...factors, ...contingency, ...numeric, ...variants };
